/**:
  ros__parameters:

    # select a Kalman Filter from supported options
    filter_type: "LKF" # options: LKF, EKF

    # subscribed topics for kitti raw dataset
    gnss_topic: "/kitti/oxts/gps/fix"
    imu_topic: "/kitti/oxts/imu"

    # published topics
    odometry_topic: "/filter/odometry"
    trajectory_topic: "/filter/trajectory"
    fused_gnss_topic: "/filter/fix"

    # frames (ROS REP-105)
    world_frame: "earth"
    map_frame: "map"
    body_frame: "base_link"

    # datum: initial Geodetic point (lat, lon, alt)
    use_datum: false
    datum: [38.43886389, 27.25458333, 0.0]